import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { Footer } from "@/components/Footercomponent/footer";
import { Header } from "@/components/HeaderComponent/header";
import AuthModal from "@/components/Auth/AuthModal";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.variable} antialiased`}>
        <Header/>
        <AuthModal/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
